CREATE TABLE USER_SYSTEM(
	ID VARCHAR(11) PRIMARY KEY,
	EMAIL VARCHAR(51),
	FIRST_NAME NVARCHAR(11),
	LAST_NAME NVARCHAR(11),
	CREATED_AT DATETIME,
	MODIFIED_AT DATETIME
)

CREATE TABLE ACCOUNT(
	ID VARCHAR(11) PRIMARY KEY,
	USER_ID VARCHAR(11) REFERENCES USER_SYSTEM(ID),
	PASSWORD TEXT,
	ROLE VARCHAR(11),
	MODIFIED_AT DATETIME
)

CREATE TABLE BLOG(
	ID VARCHAR(11) PRIMARY KEY,
	USER_ID VARCHAR(11) REFERENCES USER_SYSTEM(ID),
	TITLE TEXT,
	INTRODUCTION TEXT,
	CONTENT TEXT,
	CREATED_AT DATETIME,
	MODIFIED_AT DATETIME
)


ALTER TABLE BLOG ADD NUM_VIEWS INT

CREATE TABLE COMMENT(
	ID VARCHAR(21) PRIMARY KEY,
	USER_ID VARCHAR(11) REFERENCES USER_SYSTEM(ID),
	BLOG_ID VARCHAR(11) REFERENCES BLOG(ID),
	REPLY VARCHAR(21) REFERENCES COMMENT(ID),
	CONTENT TEXT,
	CREATED_AT DATETIME,
	MODIFIED_AT DATETIME
)

CREATE TABLE MEDIA(
	ID VARCHAR(21) PRIMARY KEY,
	BLOG_ID VARCHAR(11) REFERENCES BLOG(ID)
)

drop table media
drop table comment

delete from blog

SELECT * FROM USER_SYSTEM
SELECT * FROM ACCOUNT
SELECT * FROM BLOG

select * from comment

delete from blog where id = 'olsmdugik1'

delete from blog

UPDATE BLOG SET NUM_VIEWS = 0