###
POST http://localhost:5200/server/user
Content-Type: application/json

{
    "email": "nguyentri.alan@gmail.com",
    "firstName": "nguyen",
    "lastName": "tri",
    "password": "123456",
    "role": "admin"
}

###
POST http://localhost:5200/server/account/auth
Content-Type: application/json

{
    "email": "nguyentri.alan@gmail.com",
    "password": "123456"
}


###
GET http://localhost:5200/server/account/auth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFkcGh2MWZxNzUiLCJuYmYiOjE2ODk5NDk3NzksImV4cCI6MTY5Nzg5ODU3OSwiaWF0IjoxNjg5OTQ5Nzc5fQ.YpDG_ef93wgHVV0ivl3zYd69brieqFTzLVnVckAxLqY


###
POST http://localhost:5200/server/blog/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFkcGh2MWZxNzUiLCJuYmYiOjE2ODk5NDk3NzksImV4cCI6MTY5Nzg5ODU3OSwiaWF0IjoxNjg5OTQ5Nzc5fQ.YpDG_ef93wgHVV0ivl3zYd69brieqFTzLVnVckAxLqY

{
    "title": "test 2",
    "introduction": "introduction test",
    "content": "content test"
}

###
GET http://localhost:5200/server/blog/all
Content-Type: application/json
